### ISSUE TITLE
No breeze.py

### ISSUE THREAD

**Issue by chaosink** [XLTools/BreezeStyleSheets#1]
`dark.py` and `light.py` need `breeze.py` which doesn't exist.

And, `app->setStyleSheet()` should be `app.setStyleSheet()`.

**Comment by Alexhuszagh** [comment]
I'm busy finishing my thesis but thank you for the fix. I will be notifying myself to fix this in 10 days, after I finish.

**Comment by Alexhuszagh** [comment]
Fixed, sorry for the delay.
