### ISSUE TITLE
qt.svg can't open some svg files

### ISSUE THREAD

**Issue by stlfatboy** [XLTools/BreezeStyleSheets#7]
qt.svg: Cannot open file ':/dark/transparent.svg', because: No such file or directory
qt.svg: Cannot open file ':/dark/transparent.svg', because: No such file or directory
qt.svg: Cannot open file ':/dark/transparent.svg', because: No such file or directory
qt.svg: Cannot open file ':/dark/transparent.svg', because: No such file or directory
qt.svg: Cannot open file ':/dark/down_arrow.svg', because: No such file or directory
qt.svg: Cannot open file ':/dark/down_arrow.svg', because: No such file or directory

Style seems applied sucessfully, but some details lost.

I'm using Qt5.11 with C++ on msvc14.

THX

**Comment by Alexhuszagh** [comment]
I did many optimizations to try to minimize the file size, but the transparent SVGs are actually invalid, since they use an empty element rather than start/end elements.

For example, they're:

```xml
<svg width="64" height="64"/>
```

Rather than:

```xml
<svg width="64" height="64">
</svg>
```

It's quite possible the new XML parser does not recognize these files.

**Comment by Alexhuszagh** [comment]
It might be more than just that, I have a Qt5.11.1 install on Linux, let me check it out. I might have to add more metadata to the SVG files, which I'll gladly do as need be.

**Comment by stlfatboy** [comment]
I should check more carefully about the url in qss file.
It start to load those SVG files when I manually changed those urls to the runtime path. Because install directory is messed up by myself with cmake. 

Thank you for the checking and reply. Really good work there.

**Comment by Alexhuszagh** [comment]
Glad to hear everything's working then! If it's not, just comment and I'll re-open the issue.
